kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-monitoring-ns
subjects:
  - kind: Group
    name: groupQA
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-dev
  apiGroup: rbac.authorization.k8s.io

